name: Playwright & Kubernetes

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Check Cluster
        run: |
          kubectl get nodes

      - name: Deploy Online Boutique
        run: |
          kubectl apply -f app/online-boutique/release/kubernetes-manifests.yaml

      - name: Wait for Pods
        run: |
          kubectl wait --for=condition=Ready pod --all --timeout=600s

      - name: Verify Pods
        run: |
          kubectl get pods

      - name: Verify Services
        run: |
          kubectl get svc